# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
# Also copy any subfolder files for build
COPY src ./src

RUN npm install --production=false --ignore-scripts \
    && npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Expose port if any (not specified; MCP uses stdio)

# Default command (overridden by Smithery)
CMD ["node", "dist/server.js"]
